define([], function () {
  return {
    "AllDayEventLabel": "All Day Event",
    "AddButton": "Add",
    "AddItemLabel": "Add item",
    "ByDayDayNames": ["day", "weekday", "weekend day", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    "ByDayNumberNames": ["first", "second", "third", "fourth", "last"],
    "CancelButton": "Cancel",
    "CloseButton": "Close",
    "DailyFrequencyPrefixLabel": "Every",
    "DailyFrequencySuffixLabel": "day(s)",
    "DailyLabel": "Daily",
    "DateFormat": "m/d/yyyy",
    "DateTimeFormat": "m/d/yyyy HH:MM",
    "DateTimeLabel": "Date/Time",
    "DateWeekdayLabel": "Every weekday",
    "DayFormat": "d",
    "DayNames": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "DayShortNames": ["S", "M", "T", "W", "T", "F", "S"],
    "DeleteButton": "Delete",
    "EditButton": "Edit",
    "EditItemLabel": "Edit item",
    "EndDateLabel": "End date",
    "GoToTodayLabel": "Go to today",
    "HourNames": ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
    "ListNameLabel": "List name",
    "LocationLabel": "Location",
    "MinuteNames": ["00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"],
    "MonthlyByDayPrefixLabel": "The",
    "MonthlyByDaySuffixLabel": "",
    "MonthlyDayPrefixLabel": "Day",
    "MonthlyDaySuffixLabel": "",
    "MonthlyFrequencyPrefixLabel": "Every",
    "MonthlyFrequencySuffixLabel": "month(s)",
    "MonthlyLabel": "Monthly",
    "MonthNames": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "MonthShortNames": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "NoListSelectedError": "No list selected. Please edit the web part and select the list.",
    "NoTitleLabel": "no title",
    "RecurrenceDailyLabel": "Every day(s)",
    "RecurrenceLabel": "Recurrence",
    "RecurrenceMonthlyLabel": "Every month(s)",
    "RecurrenceWeeklyLabel": "Every week(s)",
    "RecurrenceYearlyLabel": "Every year",
    "RepeatForeverLabel": "No end date",
    "RepeatInstancePrefixLabel": "End after",
    "RepeatInstanceSuffixLabel": "occurrence(s)",
    "SaveButton": "Save",
    "StartDateLabel": "Start date",
    "TitleLabel": "Title",
    "WeeklyFrequencyPrefixLabel": "Every",
    "WeeklyFrequencySuffixLabel": "week(s)",
    "WeeklyLabel": "Weekly",
    "YearFormat": "yyyy",
    "YearlyByDayPrefixLabel": "The",
    "YearlyByDaySuffixLabel": "",
    "YearlyDayPrefixLabel": "Day",
    "YearlyDaySuffixLabel": "",
    "YearlyLabel": "Yearly",
    "YearlyMonthPrefixLabel": "Every",
    "YearlyMonthSuffixLabel": "",
    "YearMonthFormat": "mmm yyyy"
  }
});
