define([], function () {
  return {
    "AllDayEventLabel": "終日のイベント",
    "AddButton": "追加",
    "AddItemLabel": "アイテムの追加",
    "CancelButton": "キャンセル",
    "DateFormat": "yyyy/m/d",
    "DateTimeFormat": "yyyy/m/d HH:MM",
    "DateTimeLabel": "日時",
    "DayFormat": "d",
    "DayNames": ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"],
    "DayShortNames": ["日", "月", "火", "水", "木", "金", "土"],
    "DeleteButton": "削除",
    "EditButton": "編集",
    "EditItemLabel": "アイテムの編集",
    "GoToTodayLabel": "今日",
    "HourNames": ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
    "ListNameLabel": "リスト名",
    "LocationLabel": "場所",
    "MinuteNames": ["00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"],
    "MonthNames": ["1 月", "2 月", "3 月", "4 月", "5 月", "6 月", "7 月", "8 月", "9 月", "10 月", "11 月", "12 月"],
    "MonthShortNames": ["1 月", "2 月", "3 月", "4 月", "5 月", "6 月", "7 月", "8 月", "9 月", "10 月", "11 月", "12 月"],
    "NoListSelectedError": "リストが選択されていません。Web パーツを編集してリストを選択してください。",
    "NoTitleLabel": "タイトルなし",
    "RecurrenceDailyLabel": "毎日",
    "RecurrenceLabel": "繰り返し",
    "RecurrenceMonthlyLabel": "毎月",
    "RecurrenceWeeklyLabel": "毎週",
    "RecurrenceYearlyLabel": "毎年",
    "SaveButton": "保存",
    "TitleLabel": "タイトル",
    "YearFormat": "yyyy 年",
    "YearMonthFormat": "yyyy 年 m 月"
  }
});
