define([], function () {
  return {
    "AllDayEventLabel": "終日のイベント",
    "AddButton": "追加",
    "AddItemLabel": "アイテムの追加",
    "ByDayDayNames": ["日", "平日", "週末", "日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"],
    "ByDayNumberNames": ["第 1", "第 2", "第 3", "第 4", "最終"],
    "CancelButton": "キャンセル",
    "CloseButton": "閉じる",
    "DailyFrequencyPrefixLabel": "",
    "DailyFrequencySuffixLabel": "日おき",
    "DailyLabel": "日単位",
    "DateFormat": "yyyy/m/d",
    "DateTimeFormat": "yyyy/m/d HH:MM",
    "DateTimeLabel": "日時",
    "DateWeekdayLabel": "すべての平日",
    "DayFormat": "d",
    "DayNames": ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"],
    "DayShortNames": ["日", "月", "火", "水", "木", "金", "土"],
    "DeleteButton": "削除",
    "EditButton": "編集",
    "EditItemLabel": "アイテムの編集",
    "EndDateLabel": "終了日",
    "GoToTodayLabel": "今日",
    "HourNames": ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
    "ListNameLabel": "リスト名",
    "LocationLabel": "場所",
    "MinuteNames": ["00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"],
    "MonthlyByDayPrefixLabel": "",
    "MonthlyByDaySuffixLabel": "",
    "MonthlyDayPrefixLabel": "",
    "MonthlyDaySuffixLabel": "日",
    "MonthlyFrequencyPrefixLabel": "",
    "MonthlyFrequencySuffixLabel": "か月おき",
    "MonthlyLabel": "月単位",
    "MonthNames": ["1 月", "2 月", "3 月", "4 月", "5 月", "6 月", "7 月", "8 月", "9 月", "10 月", "11 月", "12 月"],
    "MonthShortNames": ["1 月", "2 月", "3 月", "4 月", "5 月", "6 月", "7 月", "8 月", "9 月", "10 月", "11 月", "12 月"],
    "NoListSelectedError": "リストが選択されていません。Web パーツを編集してリストを選択してください。",
    "NoTitleLabel": "タイトルなし",
    "RecurrenceDailyLabel": "毎日",
    "RecurrenceLabel": "繰り返し",
    "RecurrenceMonthlyLabel": "毎月",
    "RecurrenceWeeklyLabel": "毎週",
    "RecurrenceYearlyLabel": "毎年",
    "RepeatForeverLabel": "終了日なし",
    "RepeatInstancePrefixLabel": "繰り返し",
    "RepeatInstanceSuffixLabel": "回",
    "SaveButton": "保存",
    "StartDateLabel": "開始日",
    "TitleLabel": "タイトル",
    "WeeklyFrequencyPrefixLabel": "",
    "WeeklyFrequencySuffixLabel": "週おき",
    "WeeklyLabel": "週単位",
    "YearFormat": "yyyy 年",
    "YearlyByDayPrefixLabel": "",
    "YearlyByDaySuffixLabel": "",
    "YearlyDayPrefixLabel": "",
    "YearlyDaySuffixLabel": "日",
    "YearlyLabel": "年単位",
    "YearlyMonthPrefixLabel": "毎年",
    "YearlyMonthSuffixLabel": "",
    "YearMonthFormat": "yyyy 年 m 月"
  }
});
