declare interface ICalendarWebPartStrings {
  AllDayEventLabel: string;
  AddButton: string;
  AddItemLabel: string;
  ByDayDayNames: string[];
  ByDayNumberNames: string[];
  CancelButton: string;
  CloseButton: string;
  DailyFrequencyPrefixLabel: string;
  DailyFrequencySuffixLabel: string;
  DailyLabel: string;
  DateFormat: string;
  DateTimeFormat: string;
  DateTimeLabel: string;
  DateWeekdayLabel: string;
  DayFormat: string;
  DayNames: string[];
  DayShortNames: string[];
  DeleteButton: string;
  EditButton: string;
  EditItemLabel: string;
  EndDateLabel: string;
  GoToTodayLabel: string;
  HourNames: string[];
  ListNameLabel: string;
  LocationLabel: string;
  MinuteNames: string[];
  MonthlyByDayPrefixLabel: string;
  MonthlyByDaySuffixLabel: string;
  MonthlyDayPrefixLabel: string;
  MonthlyDaySuffixLabel: string;
  MonthlyFrequencyPrefixLabel: string;
  MonthlyFrequencySuffixLabel: string;
  MonthlyLabel: string;
  MonthNames: string[];
  MonthShortNames: string[];
  NoListSelectedError: string;
  NoTitleLabel: string;
  RecurrenceDailyLabel: string;
  RecurrenceLabel: string;
  RecurrenceMonthlyLabel: string;
  RecurrenceWeeklyLabel: string;
  RecurrenceYearlyLabel: string;
  RepeatForeverLabel: string;
  RepeatInstancePrefixLabel: string;
  RepeatInstanceSuffixLabel: string;
  SaveButton: string;
  StartDateLabel: string;
  TitleLabel: string;
  WeeklyFrequencyPrefixLabel: string;
  WeeklyFrequencySuffixLabel: string;
  WeeklyLabel: string;
  YearFormat: string;
  YearlyByDayPrefixLabel: string;
  YearlyByDaySuffixLabel: string;
  YearlyDayPrefixLabel: string;
  YearlyDaySuffixLabel: string;
  YearlyLabel: string;
  YearlyMonthPrefixLabel: string;
  YearlyMonthSuffixLabel: string;
  YearMonthFormat: string;
}

declare module 'CalendarWebPartStrings' {
  const strings: ICalendarWebPartStrings;
  export = strings;
}
